export const printElement = (elementId: string, title: string): void => {
  const el = document.getElementById(elementId);
  if (!el) { alert("Could not find content to print."); return; }
  const htmlContent = el.innerHTML;
  const printWindow = window.open("", "", "width=900,height=650");
  if (!printWindow) return;
  const logoUrl = window.location.origin + "/Logo.jpeg";
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const timeStr = now.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" });
  const css = [
    "@page { size: A4 portrait; margin: 15mm; }",
    "body { font-family: Segoe UI,Arial,sans-serif; font-size:12px; color:#1e293b; -webkit-print-color-adjust:exact; print-color-adjust:exact; }",
    ".doc-header { display:flex; align-items:center; justify-content:space-between; border-bottom:3px solid #0d3233; padding-bottom:15px; margin-bottom:25px; }",
    ".doc-logo { height:80px; width:auto; object-fit:contain; }",
    ".doc-school { text-align:right; }",
    ".doc-name { font-size:22px; font-weight:800; color:#0d3233; margin:0 0 5px 0; }",
    ".doc-contact { font-size:11px; color:#475569; margin:2px 0; }",
    ".doc-title { text-align:center; font-size:18px; font-weight:bold; color:#0f172a; margin-bottom:15px; text-transform:uppercase; letter-spacing:1px; }",
    ".doc-meta { display:flex; justify-content:space-between; font-size:11px; color:#64748b; margin-bottom:15px; }",
    "table { width:100%; border-collapse:collapse; margin-top:10px; }",
    "th,td { border:1px solid #cbd5e1; padding:10px 8px; text-align:left; }",
    "th { background-color:#0d3233; color:white; font-weight:600; font-size:11px; text-transform:uppercase; }",
    "tr:nth-child(even) { background-color:#f8fafc; }",
    "button { display:none !important; }",
    ".doc-footer { margin-top:30px; font-size:10px; text-align:center; color:#94a3b8; border-top:1px solid #e2e8f0; padding-top:10px; }",
  ].join(" ");
  const html = "<!DOCTYPE html><html><head><title>" + title + "</title><style>" + css + "</style></head><body>"
    + "<div class='doc-header'><img src='" + logoUrl + "' class='doc-logo' alt='Logo'/><div class='doc-school'>"
    + "<h1 class='doc-name'>Wadajir Technical and Training Institute</h1>"
    + "<p class='doc-contact'>Madina - Wadajir - Aargada Hormuud</p>"
    + "<p class='doc-contact'>Phone: 615 716 373 - 689 | Email: wadajirtti@gmail.com</p>"
    + "</div></div>"
    + "<div class='doc-title'>" + title + "</div>"
    + "<div class='doc-meta'><span>Generated on: " + dateStr + " at " + timeStr + "</span></div>"
    + "<div>" + htmlContent + "</div>"
    + "<div class='doc-footer'>Wadajir Technical and Training Institute - Official Document - Generated by Management System</div>"
    + "<scr" + "ipt>window.onload=function(){setTimeout(function(){window.print();window.close();},500);};<" + "/script>"
    + "</body></html>";
  printWindow.document.write(html);
  printWindow.document.close();
};
